- name: Make initial vol_item_filter empty
  set_fact:
    vol_item_filter: {}

- name: Create the filter tags from item tags dict
  set_fact:
    vol_item_filter: "{{ vol_item_filter|combine({'tag:'+item.key: item.value }) }}"
  with_dict: "{{ vol_item.tags }}"

- name: Detect if vol exists
  ec2_vol_facts:
    profile: "{{ profile|default(omit) }}"
    region: "{{ region|default(omit) }}"
    filters: "{{ vol_item_filter }}"
  register: get_vol_facts_out
