- include_role:
   name: aws_profile_account
  vars:
# iam role arn for this ec2 I am running to assume so that I have the
# permission to do this tasks
    aws_profile_account_role_arn: "{{ profile_account_role_arn|default() }}"
    aws_profile_account_role_session_name: 'role: ec2_persistent_volume'
    aws_profile_account_region: "{{ profile_account_region|default(region|default()) }}"
  when: not profile|default()

- name: set credentials fact
  set_fact:
    sts_creds: "{{ (sts_result|default({})).sts_creds|default({}) }}"
  no_log: yes

- include_tasks: "{{ stage }}-vol.yml"
  with_items: "{{ ec2_persistent_volumes|default([]) }}"
  loop_control:
    loop_var: vol_item
